feat(reporter): :sparkles: Add Playwright Reporter
buildkite/test-collector-javascript pull request #68
Opened 2023-09-22 19:28 UTC by whizzzkid

Closes: #67

2023-09-22 19:32 UTC, tstannard approved these changes

2023-09-25 20:41 UTC, nprizal commented
Hi @whizzzkid, thanks for opening this PR. I'll raise this to the product team and come back to you.

2023-09-26 22:17 UTC, nprizal commented on playwright/reporter.js
> +      'failure_expanded': testResult.errors,
`failure_expanded` expects an array of object with `expanded: Array<string>` and `backtrace: Array<string>` properties. You can see the documentation [here](https://buildkite.com/docs/test-analytics/importing-json#json-test-results-data-reference-failure-expanded-objects).

Maybe we can map and transform the `testResult.errors` to something like this?
```suggestion
      'failure_expanded': testResult.errors.map(error => ({
        expanded: error.message.split("\n"),
        backtrace: error.stack.split("\n")
      })),
```

2023-09-26 22:18 UTC, nprizal commented on playwright/reporter.js
> +      'failure_reason': testResult.error,
`failure_reason` expects a `string`. You can see the documentation [here](https://buildkite.com/docs/test-analytics/importing-json#json-test-results-data-reference-test-result-objects).
```suggestion
      'failure_reason': testResult.error.message,
```

2023-09-26 22:44 UTC, nprizal requested changes
Hi @whizzzkid, our team is happy to add Playwright support to our Javascript test collector. 

Could you update the [README](https://github.com/buildkite/test-collector-javascript#-installing) , and write a e2e test & example? You can refer to this [file](https://github.com/buildkite/test-collector-javascript#-installing) to implement the e2e test.

2023-09-27 04:29 UTC, nprizal commented
@whizzzkid I pushed a commit in the `origin` to fix the test result value to match what was expected by Test Analytics.
https://github.com/buildkite/test-collector-javascript/commit/d1d2d1bd9ba206010b2b0676a1720b3010a1f72a. Feel free to continue from this.

2023-10-02 22:04 UTC, nprizal commented
@whizzzkid I've fixed the reporter and added e2e test and example in my PR https://github.com/buildkite/test-collector-javascript/pull/72, could you review this PR as well?

2023-10-05 22:53 UTC, merged